export enum FrameworksName {
  iso = "iOS",
  android = "Android",
  javascript = "JavaScript",
  react = "React",
  cordova = "Cordova",
  xamarin = "Xamarin",
  flutter = "Flutter",
  net = ".NET",
  capacitor = "Capacitor",
  titanium = "Titanium",
  linux = "Linux",
  xamarinIos = "Xamarin iOS",
  xamarinAndroid = "Xamarin android",
  netAndroid = ".NET Android",
  netIos = ".NET iOS",
  netParent = "NET",
  xamarinParent = "Xamarin",
}
