export enum FrameworksName {
  ios = "iOS",
  android = "Android",
  web = "JavaScript",
  react = "React",
  cordova = "Cordova",
  xamarin = "Xamarin Forms",
  flutter = "Flutter",
  net = ".NET",
  capacitor = "Capacitor",
  titanium = "Titanium",
  linux = "Linux",
  xamarinIos = "Xamarin iOS",
  xamarinAndroid = "Xamarin Android",
  netAndroid = ".NET Android",
  netIos = ".NET iOS",
  netParent = "NET",
  xamarinParent = "Xamarin",
}
